### ISSUE TITLE
Feature request: Please allow user to change the margin between columns

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#113]
When the workbench has a large number of toolbar icons, the ribbon becomes too wide for the screen.
It would be great if we can compress the columns a little to accommodate all columns within the screen's width.

Kindly provide a control to change the margin  between columns.

**Comment by julianjc84** [comment]
I too would like this

**Comment by APEbbers** [comment]
Note to self: Look into custom class for RibbonToolButton to make left alignment of icon possible.

**Comment by raindropsfromsky** [comment]
> make left alignment of icon possible.

Well, if the width of each column is unchanged, the left-alignment (vs center-alignment) will not result in any compaction of display, because all columns would still occupy the same width in both cases.

So the benefit would come only if the columns are made narrower.

**Comment by raindropsfromsky** [comment]
On closer inspoection, are we having different icon sizes?

Compare these two toolbars, for example:
![image](https://github.com/user-attachments/assets/31bd0b31-cc37-43b9-9925-821c7e09bc33)
![image](https://github.com/user-attachments/assets/a08d8a6c-60bf-4a5e-9f2e-e1ad2a1e0995)

The apparent spacing between different column looks different!

**Comment by APEbbers** [comment]
Hi,

No the icon sizes are the same. Maybe there is som difference in the icons themselves or it is just because of the shape of fasteners that looks smaller. If the icons themselves are smaller or thicker, it is then an issue for that particular workbench.

I don't have set any icon size for a specific workbench. The ribbon just loads them as they are.
