### ISSUE TITLE
Unable to change the order in which the WBs appear in the ribbon (it does not follow either the Ribbon setting or the Addon Manager setting).

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#154]
I am unable to change the WBs' order in the ribbon.
- It does not follow the Ribbon or Addon Manager settings.

The WB toolbar appears as follows:
![image](https://github.com/user-attachments/assets/81feaa2b-e816-4915-abeb-4878783d8fb5)

The sequence in the Addon Manager is set as follows:
![image](https://github.com/user-attachments/assets/c8dca25e-d410-4d3a-bc01-fb57f58b21dd)

The sequence in the Ribbon Layout is set as follows:
![image](https://github.com/user-attachments/assets/fdc00ceb-8f35-47a9-b877-ecbcc84fcdaa)

I restarted FC several times, but the order in the WB toolbar does not match either of the two settings. **[BUG#1]**

In fact, the Ribbon layout must not duplicate what Addon Manager does.
Having two different UIs for the same purpose creates confusion! **[BUG#2]**
(Logically, which setting should override the other?)

My configuration is as follows:

OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.39287 (Git) Conda
Build type: Release
Branch: main
Hash: b5a43eb2208b91feb76b2cc363e3956922c3ad75
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CurvedShapes 1.0.13
  * Curves 0.6.51
  * fasteners 0.5.31
  * FreeCAD-Ribbon 1.4.5.3
  * SearchBar 1.0.2
  * sheetmetal 0.5.8

**Comment by APEbbers** [comment]
Hi, 

This is fixed with version 1.4.6. For the moment you can now order the workbenches in the preferences settings of FC itself.
With the update of the layout dialog, I"ll add this setting to it. Seems indeed more logical.

One note: In case you have both the Assembly WB and the Assembly4 WB enabled. The Assembly will alwasy placed before Assembly4. Otherwise the wrong panel will be loaded. (both have the same titles for a panel)
