### ISSUE TITLE
Small errors in padding and buttons 

### ISSUE THREAD

**Issue by MarcelP102** [APEbbers/FreeCAD-Ribbon#176]
Hi, I noticed some places where there seems to be to much padding.

Below the ribbon:
![afbeelding](https://github.com/user-attachments/assets/26f0bb31-9f77-4904-95f3-2f29dabff055)

At the right side of the buttons (large, medium and small) there is always to much space, making the button off-center. I think you always reserve space for the dropdown button, also when they are not used. I would advise to only make padding when there is a dropdown. And also make the padding at both sides smaller. See here compared to word:
![afbeelding](https://github.com/user-attachments/assets/262b01c9-3bad-4d1b-97ba-126c8ae01884)
vs
![afbeelding](https://github.com/user-attachments/assets/ef0678f8-eb20-4418-a16f-22df3af4fad1)

Left and right side of the separator:

Good:
![afbeelding](https://github.com/user-attachments/assets/5a11d050-0bc8-45c7-96d4-2a59903ce9cc)

Bad:
![afbeelding](https://github.com/user-attachments/assets/01e6ccfd-8429-49b0-b960-5a764afa41bf)

Icons become smaller when hovering the mouse:
![afbeelding](https://github.com/user-attachments/assets/02aec45c-c481-4789-a930-ec817433f035)

perhaps it's nicer to show the background of the button in a dark color instead of a outline when hovering, like word:
![afbeelding](https://github.com/user-attachments/assets/158dad75-88b8-4cd2-b18c-6012e3b9c7be)

Contour of button is not fully displayed:
![afbeelding](https://github.com/user-attachments/assets/75aee52c-5f64-4f43-88d8-b65b70788fd2)

Separator color/thickness is not the same:
![afbeelding](https://github.com/user-attachments/assets/410eedd2-8432-43ac-81b9-4a7765af6634)

Thanks in advance!

**Comment by APEbbers** [comment]
Hi,

Thanks for the suggetions! Regarding the padding, the Ribbon buttons are based on QToolbuttons, which centers the icons. It is not possible to left align an icon on a QToolbutton with CSS. I've planned to create a custom class for the buttons to be able to align the icons. 

I'm working on the padding below the ribbon. On my system, from size 30 onwards, it seems ok. Smaller and a "padding" appears. i'm looking into it.

Regarding the disappearing outline: which sizes have you set? below is a picture with size 20 for small buttons from my system:
![image](https://github.com/user-attachments/assets/1505fe81-d74b-4581-bea7-6c9564626d84)

Which version of the ribbon do you have installed and which OS version are you using? (I'm checking because I've tested it with both Windows 11 and Linux mint and it seems fine)

Good idea to use a background instead of a border. I'll implement that for the next release.

**Comment by MarcelP102** [comment]
Hi,

I use Windows 11, Freecad 1.0, Ribbon 1.4.10 and these settings:
![afbeelding](https://github.com/user-attachments/assets/3aa1d8b5-d397-465f-96f9-92b19bf1d631)

I updated to 1.4.14 that fixes the padding below the ribbon, thanks.


Looking forward to the improvements :)

**Comment by MarcelP102** [comment]
I now got the development branch working, already a big improvement with the icons padding, great work!
