### ISSUE TITLE
Option to enter the number of rows and quit the bottom panel names.

### ISSUE THREAD

**Issue by dgrabulosa** [APEbbers/FreeCAD-Ribbon#182]
With all small icons, there are 3 rows in the ribbon, and a lot of space in the end it can fill if y can select 2 rows for example.
The other ting is the panel names, if I can turn off I can reduce the width of the ribbon and add mote space to the main screen.
![Captura de pantalla 2024-12-01 020431](https://github.com/user-attachments/assets/d69bf40f-0a54-4bfe-8de0-93dbd3606763)

**Comment by MarcelP102** [comment]
It wasn't clear for me either but changing the icons to medium in the Ribbon layout - Ribbon design tab makes in into 2 rows. So:
Large = 1 row
Medium = 2 rows
Small = 3 rows

Hiding the title would be a nice addition.

**Comment by dgrabulosa** [comment]
The rows control is important to optimize the available space: with 3 rows, the ribbon leaves near 50 % without icons. In my part design workbench.
If I can configure 2 rows and hide section titles, I can recovery near 30%-40% of the space occupied with the icons of the ribbon.

**Comment by APEbbers** [comment]
Hi,

I've compared several programs with a ribbon and they all have a panel title. Also I believe thatpanel titles are an important part of a ribbon design.  The are used to group different type of functions like with toolbars.
Combined with the fact that since the latest release of the ribbon, the titles are much shorter, the titles remain present.

kind regards,

P.S.: below two examples. (Outlook and SolidEdge)
![image](https://github.com/user-attachments/assets/487abae3-006b-4b65-85a1-d1bd453a45ed)
![image](https://github.com/user-attachments/assets/818797cc-5488-4b0e-bb74-7616a7083f65)
