### ISSUE TITLE
There is no intuitive way to use the scripts provided in the menu

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#193]
Although the menu provides scripts through menus, we cannot execute them from there.

![image](https://github.com/user-attachments/assets/c6da01dc-4d47-4047-ab91-95a20da63555)

When we select a script, it is opened in a file.
- We cannot edit it from within FC 
- FC does not provide bulk-editing tools such as find-and-replace.
- We cannot execute the script from FC itself.
- The help text (in green) does not tell us how to edit and run the script file.

**Desired:**
It would be better to provide a URI to the script file, so that the user can open that file and edit it externally.
Also provide a menu to execute the script.

**Comment by APEbbers** [comment]
Hi, you can actually edit them from within FreeCAD. but yes without bulk editing tools. However the script can easily be adapted following the comments in the script (green text in picture below). you can just type False instead of True, etc.

To run the scripts, you open the file in FreeCAD. Then go to "Macro -> Excecute macro (ctrl + F6). This is also good to now if you want  to run macros from downloaded from the add-on manager.

In the next release, the functions are available in the layout menu. So you don't have to run the scripts anymore.
Most of the new functions are already available in the develop branch.

kind regards,

![image](https://github.com/user-attachments/assets/d5840e3b-d703-420f-b4e7-0f66ebc4beb4)

**Comment by raindropsfromsky** [comment]
Hi

Thanks for the response!

It will be great if you provide these tips as comments in the scripts:
- How to edit the script from within FC 
- How to edit the script externally (provide full path)
- How to execute the script

Othehrwise, most users will not know what to do next.
