### ISSUE TITLE
Bug: Replace hardcoded icon paths with current paths

### ISSUE THREAD

**Issue by hasecilu** [APEbbers/FreeCAD-Ribbon#93]
When the custom STEMFIE Ribbon was created the used icons were hardcoded on the JSON file, as consequence now that I'm updating bad icons on the WB the new icons instead of appearing it does appear a `?` symbol.

 The other 3 icons that DO APPEAR is because those commands were renamed, but the ones that conserved the name still try to use the old hardcoded value.

Also I think would be better to use relative paths.

![image](https://github.com/user-attachments/assets/d1dae6d1-282c-4c8f-9dc2-172f7cce1c1c)

**Comment by APEbbers** [comment]
Hi,

That is strange because the icons are retrieved from FreeCAD. They are stored in the JSON file for reference.
See belowe the code that I use. Only when the action itself has no Icon, it uses the name from the JSON file to retrieve it from FreeCAD. Perhaps it helps if you remove the hardcoded lines from the json file? 

When you open the design menu, are the icons also missing? Because the design menu always takes the icon from the command and not from the json file.

![image](https://github.com/user-attachments/assets/4b068830-513a-44c0-927b-0d7e227757bb)

The action comes from a button in an list made of all buttons in the mainwindow:
![image](https://github.com/user-attachments/assets/fcdafebd-cedd-4e56-b655-6cdda23a90c1)

**Comment by hasecilu** [comment]
Updated to latest version and it's the same. Even the ribbon tool tries to load old icons

EDIT: OK, the icon's path are what the WB dev assigned to pixmap, most WB do not use `FreeCADGui.addIconPath(ICONPATH)` which let us assig the icons without using all the path, for example on FreeGrid I use that and in the JSON file I get: `"icon": "box"` but on STEMFIE I'm not using it, hence using full path and I get: `"icon": "/home/uli/.local/share/FreeCAD/Mod/StemfieWB/freecad/stemfie/resources/icons/Brace STR STD BRT AY_icon.png"` so the recommendation is to add the icon path. I think all official WB use icons as resources but for lots of external WB is a potential issue.

![2024-11-06-115831_hyprshot](https://github.com/user-attachments/assets/d6eb647e-6472-4664-b2a0-ec7eb8c4e4cd)

**Comment by APEbbers** [comment]
I'm looking for an solution, but i find it still strange. I'm not manipulating the icons. The design menu just reads the information from FreeCAD. Some workbenches present absolute paths and other relative. Below a picture on how i get the icon pixmaps:
![image](https://github.com/user-attachments/assets/6790c72d-d39c-44fa-b03b-b51f3d1d7a5c)

I tried to force relative paths, but then other icons dissapear. I'll install your wb to do some tests.

**Comment by hasecilu** [comment]
Yes, I noticed that, check my edited comment above, probably I'll change those icons to use relative path, is possible to overwrite the icons tag on the JSON file? If the icon is read from pixmap when ribbon is created could be possible to overwrite old data.

**Comment by APEbbers** [comment]
Yes that can indeed. In the design dialog, go to the ribbon design tab. Then select the workbench and toolbar. When you then press update, the tags will be overwritten in the JSON file. 

Another option is to manually remove the tags or the complete WB from the json file.

**Comment by hasecilu** [comment]
Cool! the Update button did the trick.
![image](https://github.com/user-attachments/assets/915145dc-d885-408e-b36d-d9f51b4fe332)
