### ISSUE TITLE
FR: Large button size implementation in preferences & general ribbon improvements

### ISSUE THREAD

**Issue by SpeeQz1** [APEbbers/FreeCAD-Ribbon#97]
It would be great to have an additional option to change the size for the larger buttons as it already exists for changing small and medium ones.

Customize... -> 
![image](https://github.com/user-attachments/assets/e45412a7-f004-47d7-a4a1-e78a3613f0a7)

Some additional features to consider which would be great to have are:
* Changing the padding/margin of the buttons
* An option to somehow fit every button of a workbench on a single screen without needing to scroll to reach others
* An option to change the scrolling of workbenches from just changing the workbench to instead the scroll action to move smoothly the buttons themselves to the left or right and instead requiring a manual click to change it
* An option to customize the workbench buttons so you can fit more of them on one screen
* Draggable button groups for each workbench ( the ones separate by vertical lines )
* Right click menu when trying to click on the toolbar as it seems to be missing
* This is more of a personal idea but I haven't seen an addon have the option to put several different buttons into one singular drop down button, for example the "Create an additive primitive" drop down button from Part Design is hard coded so if there was a way with the addon to make such buttons that would be amazing.

Sorry if some of these sound a bit too much, these are just some quick ideas that came to my mind which I believe would be very helpful to other users trying out the addon.

**Comment by hasecilu** [comment]
- An option to center icons when panel is bigger that needed spaces OR even have an "smart ai-powered assistant" that when with its omniscient sense finds a panel with to much unused space automatically makes bigger the few existing icons, as a better proposal for first time creating that ribbon.

| 1 | 2 |
|:-----:|:-------:|
|![image](https://github.com/user-attachments/assets/e48ead98-030f-4bfc-af33-1dc90d252fcb)|![image](https://github.com/user-attachments/assets/ce5fd512-179f-4205-a38d-0db73c78c49e)|

- 

> An option to somehow fit every button of a workbench on a single screen without needing to scroll to reach others

Not really sure about this for example Fasteners WB have many commands, having more rows will bloat the window, bad for small screens. Of course, Fasteners WB have an option to have less icons on toolbar.

**Comment by SpeeQz1** [comment]
> Not really sure about this for example Fasteners WB have many commands, having more rows will bloat the window, bad for small screens. Of course, Fasteners WB have an option to have less icons on toolbar.

I was hoping somehow to fix this issue with my drop down buttons suggestion as using such buttons you could just fit as many as you want buttons into a single one.

Sadly the current buttons are hard coded into a singular one:

![image](https://github.com/user-attachments/assets/4d1ada84-3c45-473f-9b0a-d617863c5f7b)

**Comment by APEbbers** [comment]
Hi,

Thanks for the suggestions and ideas. I've added below some comments for explanations.

>It would be great to have an additional option to change the size for the larger buttons as it already exists for changing small and medium ones.

I had that, but with the large icons and text enabled, the text was dissapering. That's why i removed it. I'll look into this to bring it back again. Maybe I can use padding or something.  

> Changing the padding/margin of the buttons
  

Good idea. I'll put it on the list for future

> An option to somehow fit every button of a workbench on a single screen without needing to scroll to reach others
  

That will be diffucult. As @hasecilu mentioned, the fasteners wb but also the FEM wb has a lot of commands.

> An option to change the scrolling of workbenches from just changing the workbench to instead the scroll action to move smoothly the buttons themselves to the left or right and instead requiring a manual click to change it

I'look into that in that. Probally I have to find a way not to activate the tab automaticly.
  

> An option to customize the workbench buttons so you can fit more of them on one screen

i agree here with @hasecilu. I'll keep it in mind, but personally I havent seen a cad program that has a lot of rows in their ribbon.
  

>Draggable button groups for each workbench ( the ones separate by vertical lines )
Right click menu when trying to click on the toolbar as it seems to be missing
This is more of a personal idea but I haven't seen an addon have the option to put several different buttons into one singular drop down button, for example the "Create an additive primitive" drop down button from Part Design is hard coded so if there was a way with the addon to make such buttons that would be amazing.

These three are also on my wish list. I was already looking into draggable buttons, but that will be for version 2.0. 
it is possible though, but i have to look how to get it working with the pyqtribbon package. That will take some time.
At the moment, I'm focussing on bugs and UI optimalizations so that it is ready to go to the next step.

thanks again for your input!

**Comment by APEbbers** [comment]
> > Not really sure about this for example Fasteners WB have many commands, having more rows will bloat the window, bad for small screens. Of course, Fasteners WB have an option to have less icons on toolbar.
> 
> I was hoping somehow to fix this issue with my drop down buttons suggestion as using such buttons you could just fit as many as you want buttons into a single one.
> 
> Sadly the current buttons are hard coded into a singular one:
> 
> ![image](https://private-user-images.githubusercontent.com/141474274/383709057-4d1ada84-3c45-473f-9b0a-d617863c5f7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjM3MzMsIm5iZiI6MTczMDkyMzQzMywicGF0aCI6Ii8xNDE0NzQyNzQvMzgzNzA5MDU3LTRkMWFkYTg0LTNjNDUtNDczZi05YjBhLWQ2MTc4NjNjNWY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMDAzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2E5MmNjMzNkNjljNWFhZjVlZTkyNTc2MGJkMzRmMzRmMDU4ZDc4ZGRhMzYxN2M4MmUyM2RjMDM3NTUyOThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.70LGKl1Hn1vUiMllPAzpl_YyvFCB-hWr7TvXzY4iGFk)

I think they are reacable with code.  the commands are QActions. If there are more then one, there is a list of actions.
below a screenshot with a part of the code used to created the optionpanel:
![image](https://github.com/user-attachments/assets/b2ee81dc-6630-4ec0-b29d-a0c15f57594b)
I like the dropdown suggestion. I'll take it with, when I'm going to work on the draggable buttons

**Comment by SpeeQz1** [comment]
> > An option to customize the workbench buttons so you can fit more of them on one screen
> 
> i agree here with @hasecilu. I'll keep it in mind, but personally I havent seen a cad program that has a lot of rows in their ribbon.

It's mostly a problem for me since I have to scroll from left to right to reach the more further back workbenches and if I had a way to tweak size/margin/padding or straight up remove the text that'd be nice. Especially with how much space I have on a 1920x1080 screen.

![image](https://github.com/user-attachments/assets/cc69e117-1aea-4de0-9447-164d0c057ce7)

**Comment by APEbbers** [comment]
Hi,

In my develop branch I've overridden the scroll function for the tabbar. Now you can scroll the whole tabbar without activating the next tab. This way you can easily and fast scroll from left to right.

Can you give it a try? my develop branch is: [https://github.com/APEbbers/FreeCAD-Ribbon/tree/Develop](url)

kind regards,

**Comment by SpeeQz1** [comment]
> Hi,
> 
> In my develop branch I've overridden the scroll function for the tabbar. Now you can scroll the whole tabbar without activating the next tab. This way you can easily and fast scroll from left to right.
> 
> Can you give it a try? my develop branch is: [https://github.com/APEbbers/FreeCAD-Ribbon/tree/Develop](url)
> 
> kind regards,

Can confirm it works, but a problem seems to have appeared where the other buttons for the workbenches are being scrolled too as if the scrolling action is being read globally.

**Comment by APEbbers** [comment]
Hi,

Thanks for testing. If you mean the behavior in the video below. This actually the intension. You can activate a tab by clicking on it. The scroll function now "clicks" on the scroll buttons instead going to the next tab and activating it.
The problem is that when the tab is activated, the workbench needs to be activated as well to be properly loaded. Otherwise, the ribbon stays empty. This is the cause why the scrolling wasn't going smoothly. Because of this, I changed the scroll behaviour to scrolling the tabbar as a whole.

https://github.com/user-attachments/assets/20bdaf91-cecb-4d96-a80f-ff33da1507d4

**Comment by SpeeQz1** [comment]
This is not the problem I faced. In my case when I scrolled the workbenches the panel with the buttons bellow them "Add primitive","Create Part",etc... would also scroll left and right.

**Comment by APEbbers** [comment]
Hi 
it took me a while, but I believe that I've fixed it. Seems there is an issue with Qt and Linux. (Windows worked fine)
I've now added a check that detects if the tabbar has focus or not. And I did the same for the ribbon.

can you check again if it works now?

In my linux version, the quickaccess toolbar and right toolbar where hidden. this should also be fixed.
By the way, if you install the SearchBar addon, it will be intergrated in the right toolbar.
![image](https://github.com/user-attachments/assets/32fad2c1-616d-4088-a912-a9ae2bc35dbf)

Thanks for the help!

**Comment by SpeeQz1** [comment]
The Ribbon is gone

@APEbbers

![image](https://github.com/user-attachments/assets/b29fc89f-828b-4546-80ef-f7cf76eac170)
![image](https://github.com/user-attachments/assets/c4c0d45f-1b5c-4071-afdd-044c204755b8)

**Comment by APEbbers** [comment]
Should be fixed now

**Comment by SpeeQz1** [comment]
> Should be fixed now

It is working:
![image](https://github.com/user-attachments/assets/a7667a23-f9cb-40e5-9fae-533a99431880)

Another issue is the view which has tools like "Measure" is missing I assume that is because this version isn't still fully updated for the 1.0 build?

**Comment by APEbbers** [comment]
Good that it works.

Yes indeed this version is not fully updated yet. he assembly4 has also a measure tool with the same name which overrides the new measure tool in the design menu currently.

**Comment by APEbbers** [comment]
I just added the new measure tool to the quick access toolbar. Also the new measure tools is now present in the design menu
![image](https://github.com/user-attachments/assets/932b5cdf-4f54-4301-989e-ad5d6f1902cb)

**Comment by SpeeQz1** [comment]
> I just added the new measure tool to the quick access toolbar. Also the new measure tools is now present in the design menu ![image](https://private-user-images.githubusercontent.com/10145631/384718408-932b5cdf-4f54-4301-989e-ad5d6f1902cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjU1MDksIm5iZiI6MTczMTI2NTIwOSwicGF0aCI6Ii8xMDE0NTYzMS8zODQ3MTg0MDgtOTMyYjVjZGYtNGY1NC00MzAxLTk4OWUtYWQ1ZDZmMTkwMmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE5MDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YWNmZjQwMDE5ZWM2YmNjMGI5MTQwMjhhZDQ5NmRmNDFhMWM4NDdmODJkOTM5ZTYyMmU4NmQxNzYxMWI2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.31foabKy3_bFlpNuFC8RPh02yCPw16cw44xhHXQi6Rw)

Wouldn't it be better to place the measure tool along the other actions in a separate group next to the views?
![image](https://github.com/user-attachments/assets/724e7d3f-5e63-4f7b-a005-892390b17239)

**Comment by APEbbers** [comment]
Maybe I can create a custom toolbar/panel just for FC1.0 with measurement, units converter, macro, etc. 
I do find it a bit strange that the measurement tool is located in the view toolbar. but that is an another topic.

The view toolbar is standard excluded, but you can include it via the design menu.
![image](https://github.com/user-attachments/assets/57099d9b-b002-4c83-9b2f-e5865b327c07)

**Comment by MarcelP102** [comment]
With an 4k display the Large icons a way to big. Also the workbech selector is quite big. See:
![afbeelding](https://github.com/user-attachments/assets/d7074c80-b91c-4b75-b284-07bb0e8f117e)

**Comment by APEbbers** [comment]
hi,

Thanks for the info. The workbench selector size issue is solved in the develop branch. I've not yet a solution for the large icons without the labels disappearing but I'm working on it!

kind regards

**Comment by APEbbers** [comment]
Hi,

In the latest version of my develop branch, you can now set the icon size for the large icons.
Also you can set the size for icons in:
- quickaccess toolbar
- right toolbar
- tabbar
- Applicationbutton

**Comment by SpeeQz1** [comment]
With all the new changes, how further on your TODO list is the custom grouped button ideas, since that one could help even further with freeing up space on each individual workbench?

![image](https://github.com/user-attachments/assets/480f725e-00be-4714-8ec0-7a217b6c8f75)

Example button:
Dropdown button with the image of an "Create a cube solid" and the rest of the dropdown menu options displaying the other buttons.

Example settings:
You can make it where you have 2 additional columns for the main dropdown button (it can be small, medium or large) and then any button bellow it marked as a "Sub Button" or something similar will be placed under that dropdown.

![Image](https://github.com/user-attachments/assets/8128b4c4-f870-4bf8-95e0-b2bd3d0631a4)

**Comment by APEbbers** [comment]
Hi,

I've created a road map, so people can see what the plans are. You can find the road map here:  [https://github.com/APEbbers/FreeCAD-Ribbon/wiki/07-%E2%80%90-Road-map](url)

It is planned for the release after the upcoming release.

**Comment by SpeeQz1** [comment]
@APEbbers I saw recently 1-2 people complain on the FreeCAD discord that the default large button sizes are a bit too big.

**Comment by APEbbers** [comment]
I've implented the setting for large buttons in the develop branch.  I've one item left on my ToDo list before the next release
After that it will be available in the main branch

**Comment by MarcelP102** [comment]
Hi, I really appreciate your effort to make a nice ribbon add-on. Although we now can change the size of the icons the padding around them make the ribbon bar still huge. I think there is some room for improvement. Also when compared to MS office for example the use mostly 2 small icons above each other.

MS Word, only 100px in height:
![afbeelding](https://github.com/user-attachments/assets/d4f467b6-fa3a-413d-8f1f-b416f316c452)

Compared to your addon - 125px:
![afbeelding](https://github.com/user-attachments/assets/289d89d3-27c3-426d-8d83-9948d6f8a70e)

That 25px in height really makes a difference. Also the icons are much closer to each other in Word. 

Also the down arrow below the big icon to see sub actions instead next to the icon also save a lot of horizontal space

**Comment by APEbbers** [comment]
Hi,

Thank you for your feedback! It is appreciated.

You can use medium icons and change the size of those. small icons have always 3 rows, medium always 2, and large 1. 
Maybe I have to change the terminology to avoid confusion.

 I've updated the script for creating a ribbon structure for all workbenches at once. (CreateDefaultRibbonStructure.py) Below a screenshort from the script were you can set the icon size:
![image](https://github.com/user-attachments/assets/fae87e30-0c49-4ce9-ab31-59d5fe875603)
You can use this to set all buttons to medium and then set the size to the size of small buttons.

What type of OS are you using? I'm asking because on my laptop the buttons look like this:
![image](https://github.com/user-attachments/assets/df2b7c17-207d-4042-a97c-5aec611909ab)
On the left there are a few medium buttons for example.

I use Windows 11 with the FreeCAD dark theme. That seems better to work than OpenDark and OpenLight for me.
Below a screenshot with linux mint and the FreeCAD dark theme:
![image](https://github.com/user-attachments/assets/931757b2-73b8-4d1b-b147-fafdf615b1cd)

I'll look into creating a setting to allow the user to change the padding.
I have planned to implent the scripts into the design menu, so you can change all buttons at once from there.

I hope this helps a little bit.

kind regards

**Comment by SpeeQz1** [comment]
Do you believe you can add a pop up window for the Macro so that this can be set visually rather than having to edit the macro, it would be even better if it could be automatically brought up for the macro instead of opening the code.

**Comment by APEbbers** [comment]
I had planned to implement this as an extra tab in the design menu. Al the tools are there for design in the menu are there at the moment.  I am thinking to have a setting like: "all buttons to small" (or medium, etc)
And also per toolbar and per workbench.

Thinking about it, i can make more room on the design tab, and add extra controls for this there? keeps it visual and in one place

What do you think?

**Comment by SpeeQz1** [comment]
> I had planned to implement this as an extra tab in the design menu. Al the tools are there for design in the menu are there at the moment. I am thinking to have a setting like: "all buttons to small" (or medium, etc) And also per toolbar and per workbench.
> 
> Thinking about it, i can make more room on the design tab, and add extra controls for this there? keeps it visual and in one place
> 
> What do you think?

Sounds nice. Would it go in `Ribbon preferences` or `Ribbon layout`?

**Comment by APEbbers** [comment]
It would go in Ribbon layout. I think it is the most logical place. There all the buttons can set separately anyway

**Comment by SpeeQz1** [comment]
> It would go in Ribbon layout. I think it is the most logical place. There all the buttons can set separately anyway

In that case is there are any possibility of improving the workbench loading functionality as it takes a while for the Ribbon layout to usually load everything or is that simply something which doesn't have a code solution?

**Comment by APEbbers** [comment]
I want to look if i can adopt the serialize function of the SearchBar add-on. That add-on seems to store all the commands in a file.

**Comment by MarcelP102** [comment]
I'm using the opendark theme, will test with freecad dark this weekend. It wasn't clear for me that medium are two rows. I like the idea of being able to change them all at once. 

Thanks again!

**Comment by APEbbers** [comment]
Hi,

In my developer branch I've implemented all the main functions for the release of v1.5.0.
I'm about to start testing and add bugfixes from issues that are not fixed yet. 

But if you want to have a look, I've implemented the following functions:
Add import/export function for:
  - Ribbon layout 
  - Custom panels
  - Dropdown buttons 
- Add option to create panels from commands instead of toolbars 
- Add option to create dropdown buttons
- Add a section that implement the functions from scripts within the design menu
- Add custom Overlay function to exclude the ribbon from Overlay
- Implement serialize function from SearchBar add-on to speedup loading time for the layout dialog
- Shorten panel labels by removing workbench names
- Reduced space between the buttons

Kind regards

**Comment by hasecilu** [comment]
> In my developer branch I've implemented all the main functions for the release of v1.5.0.
> I'm about to start testing and add bugfixes from issues that are not fixed yet.

Would you say is good time to make a PR updating the translations?

**Comment by APEbbers** [comment]
yes i believe it s a good time to update the translations. Can you do the PR on the develop branch instead of the main branch?
there are a lot of differences between the two
